apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tgb-airflow-webserver
spec:
  serviceRef:
    name: {{ .Values.targetGroupBinding.serviceRef.name }}
    port: {{ .Values.targetGroupBinding.serviceRef.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupARN }}
  targetType: ip